### ISSUE TITLE
I can create a splash screen

### ISSUE THREAD

**Issue by Wasif0787** [Dtech-Dbug/MemeTem#1]
Need to install framer motion and tailwind to create a splash screen that will appears once per session

**Comment by Dtech-Dbug** [comment]
@Wasif0787 sure go for it. I liked the idea of framer for animations, very interesting! I'd love it if you would do that, also I would strongly suggest you to keep it as minimal as possible, avoid bulks as much as possible, lets not make the app heavy. 

Also, it would be really nice, if you can add a preview of your output in ur feature branch - named as preview.md or something, it would be bttr for us to visualise the change first and get into the semantics.

**Comment by Wasif0787** [comment]
Added the preview.md check the pr

**Comment by Dtech-Dbug** [comment]
@Wasif0787  find color palettes here : `https://colorhunt.co/` 

we can only include 3 colors :
- 1 primary 
- 1 secondary 
- 1 for texts (solid balck or white, if secondary is not suited)
