### ISSUE TITLE
Change the BG of the splash screen

### ISSUE THREAD

**Issue by Dtech-Dbug** [Dtech-Dbug/MemeTem#10]
the current color of the splash screen BG is very pale, 
we are aiming to give it a flare of fun and styles - simple yet elegant which is visually appealing. 

here's a list of color palettes : `https://colorhunt.co/`
we can only choose 2 colors for our theme one primary one secondary, or even get creative and use gradient bordered splash screen.

**Comment by Dtech-Dbug** [comment]
@Wasif0787 can you pick it up bro?

**Comment by Wasif0787** [comment]
i was thinking to add daisyui , it provides different themes , and also text colors for each themes , u can check from here https://daisyui.com/

**Comment by Dtech-Dbug** [comment]
@Wasif0787 sure go for it, but PLS MAKE SURE IT DONT BULK THE APP 

I REALLY LIKE THE GRADIENT THEMED TEXT in the daisyUI, can try somthing like that too to the Name - 

all in all go for it, but dont make the app heavy so that it takes several seconds to load

**Comment by Wasif0787** [comment]
https://daisyui.com/docs/themes/

let me know hwihc theme u liked

**Comment by Dtech-Dbug** [comment]
@Wasif0787 use any one that is a little soothing on the yes (maybe with a dark ish primary color like dark/luxury etc). I am confident you will pick up a nice theme (make sure its not beeming the eyes like white mode)

**Comment by Wasif0787** [comment]
I am thinking to use forest theme , what u say

**Comment by Dtech-Dbug** [comment]
@Wasif0787 sure go for it, whatever you like, no worries ;)
