### ISSUE TITLE
Make Splash Screen Use the Same Styles as the landing page

### ISSUE THREAD

**Issue by Dtech-Dbug** [Dtech-Dbug/MemeTem#11]
Let's try to make the splash screen use the same looks and feels of the landing page that Piyush Created, that way we can have consistent styles.

ref - `https://github.com/Dtech-Dbug/MemeTem/pull/7#issuecomment-2389537219`

**Comment by Dtech-Dbug** [comment]
@Wasif0787 can you pick it up for your next PR, please?

**Comment by Wasif0787** [comment]
Sure just give me some time I'll make the pr for this issue , assign me this one

**Comment by Dtech-Dbug** [comment]
done, all the best. 🤝
