### ISSUE TITLE
Emoji Confetti Showing On Every Refresh - Bug

### ISSUE THREAD

**Issue by Dtech-Dbug** [Dtech-Dbug/MemeTem#12]
right now, every refersh the emoji confettis are showing up, 
we arent looking for that. 

Ideally for now, we should _ONLY SHOW THE CONFETTIS IN THE SPLASH SCREEN_

**Comment by anuj846k** [comment]
Could you add video or screenshot , I am unable to understand the issue

**Comment by Dtech-Dbug** [comment]
https://github.com/user-attachments/assets/fc804c4d-3413-4112-a9ad-4f26dbdf34d4

the emoji showers(confetti) should ideally only happen only in the splash screen... but it also happens in the template feed, when you refresh, we need to prevent it, and ensure the confettis are not showing unnecessarily. 

Is that clear? @anuj846k
