### ISSUE TITLE
Changing Favicon and Title of Website

### ISSUE THREAD

**Issue by rishyym0927** [Dtech-Dbug/MemeTem#4]
The current website lacks a custom favicon and the title displayed in the browser tab is either outdated or not aligned with the brand. This needs to be updated to ensure better branding consistency and user recognition.

**Comment by Dtech-Dbug** [comment]
@rishyym0927 thanks a ton bro, possible for you add a snapshot or a change note? So I can visualise the change?

**Comment by namansharma3007** [comment]
@Dtech-Dbug Please assign this issue to me I can do it.

**Comment by kshitijakarsh** [comment]
hey can i take up and this and make changes?
