### ISSUE TITLE
Initializing TailwindCSS Configuration for Better UI Development

### ISSUE THREAD

**Issue by rishyym0927** [Dtech-Dbug/MemeTem#5]
Description:

TailwindCSS needs to be configured and initialized in the project to enable more efficient and responsive UI development. This will provide a utility-first approach to styling, improve design consistency, and enhance development speed.

Assign it under hacktoberfest label

**Comment by Dtech-Dbug** [comment]
@Wasif0787 and @rishyym0927  could you guys sync up and try to set it?
I think @Wasif0787 has already configured tailwind to this project, let's not duplicate efforts :) 
it would be great if you guys could sync and add the discussion / conclusion here - you can add me to the call as well, I would like to understand your visions each. 

Please see to it - again the reason i am asking for syncing is, I dont want anybody to work on something thats done and not get their PR merged, I genuinely want you all to get your PRs merged and be better contributors. 
Hope that makes sense :)

**Comment by Wasif0787** [comment]
Tailwind is already installed on the project , no need to nstall again
