### ISSUE TITLE
OnClick of Image - we should scale the image up and show a backdrop 

### ISSUE THREAD

**Issue by Dtech-Dbug** [Dtech-Dbug/MemeTem#9]
We want to introduce a feature, where you click on the templae the image should scale up with a backdrop filter, so THAT THE USER CAN SEE THE FULL IMAGE CLEARLY. 

If you are working on it, pls assign to yourself.

**Comment by Abhiraj-Sardar** [comment]
@Dtech-Dbug  
can you assign this task to me under hacktoberfest2024?

**Comment by Dtech-Dbug** [comment]
@Abhiraj-Sardar sure, on it - could make sure to do the following if you start working on it :
- clone my repo directly -> run `git pull -r` on the main branch to have latest change -> create ur feature branch with format `name-change` example `abhiraj- backdropScale` etc 

- also PLEASE PLEASE include a change note, adding a snapshot/video of ur change, so its easy for us to visualise.
